# Generated by Django 4.2.11 on 2024-04-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
