# Generated by Django 4.2.11 on 2024-04-30 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='sexe',
        ),
        migrations.AlterField(
            model_name='agent',
            name='id_agent',
            field=models.CharField(default=uuid.uuid4, max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='apc',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gouvernorat',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=1000000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='date_rendez_vous',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user1',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=1000000, primary_key=True, serialize=False, unique=True),
        ),
    ]
