# Generated by Django 4.2.9 on 2024-02-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter_app', '0004_otp_alter_user_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
