# Generated by Django 4.2.9 on 2024-02-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter_app', '0008_passwordresettoken_validity_alter_otp_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='categories/')),
            ],
        ),
    ]
