# Generated by Django 4.2.9 on 2024-02-14 00:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flutter_app', '0010_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=100000)),
                ('price', models.IntegerField(default=0)),
                ('offer_price', models.IntegerField(default=0)),
                ('delivery_charge', models.IntegerField(default=0)),
                ('star_5', models.IntegerField(default=0)),
                ('star_4', models.IntegerField(default=0)),
                ('star_3', models.IntegerField(default=0)),
                ('star_2', models.IntegerField(default=0)),
                ('star_1', models.IntegerField(default=0)),
                ('cod', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_set', to='flutter_app.category')),
            ],
        ),
    ]
