# Generated by Django 4.2.9 on 2024-02-14 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flutter_app', '0013_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/')),
                ('viewtype', models.IntegerField(choices=[(1, 'BANNER'), (2, 'SWIPER'), (3, 'GRID')])),
                ('title', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageitems_set', to='flutter_app.category')),
                ('product_options', models.ManyToManyField(blank=True, to='flutter_app.productoption')),
            ],
        ),
    ]
