# Generated by Django 4.2.9 on 2024-02-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter_app', '0009_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='categories/')),
            ],
        ),
    ]
