# Generated by Django 4.2.9 on 2024-02-14 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flutter_app', '0012_productoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='products/')),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images_set', to='flutter_app.productoption')),
            ],
        ),
    ]
